name: build

on: push

jobs:
  yarn-build:
    name: Yarn build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.18.0

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 20.18.0

      - name: Build
        shell: bash
        run: |
          yarn install
          yarn build
          
