name: build

on: push

jobs:
  yarn-build:
    name: Yarn build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.18.0

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 20.18.0

      - name: Build
        shell: bash
        run: |
          yarn install
          yarn build

      - name: Deploy
        shell: bash
        env:
          USER: ${{ secrets.SSH_USER }}
          PASS: ${{ secrets.SSH_PASS }}
        run: |
          echo "==> Local build files:"
          ls -lah build/
          sshpass -p ${PASS} scp -r -o"StrictHostKeyChecking=no" build/* ${USER}@rekavida.com:/httpdocs/todo-redux/
          echo "==> Remote files deployed:"
          sshpass -p ${PASS} ssh -o"StrictHostKeyChecking=no" ${USER}@rekavida.com 'ls -lah /httpdocs/todo-redux/'
